{user.model} quick help$: user.model_help_canvas_open()
{user.model} help who$: user.model_help_canvas_open_who()
{user.model} help why$: user.model_help_canvas_open_why()
{user.model} help how$: user.model_help_canvas_open_how()
{user.model} quick help patterns$: user.model_pattern_gui_open()
{user.model} quick help suggestions$: user.model_prompt_recipe_suggestions_gui_open()
{user.model} quick help docs$: user.gpt_help()
{user.model} quick help history$: user.request_history_drawer_toggle()
{user.model} quick help completeness$: user.model_help_canvas_open_completeness()
{user.model} quick help scope$: user.model_help_canvas_open_scope()
{user.model} quick help method$: user.model_help_canvas_open_method()
{user.model} quick help form$: user.model_help_canvas_open_form()
{user.model} quick help channel$: user.model_help_canvas_open_channel()
{user.model} quick help direction$: user.model_help_canvas_open_directional()
{user.model} quick help examples$: user.model_help_canvas_open_examples()
{user.model} quick help compact$: user.model_help_canvas_compact_on()
{user.model} quick help full$: user.model_help_canvas_compact_off()

{user.model} show grammar$: user.model_help_canvas_open_for_last_recipe()
{user.model} quick help {user.staticPrompt}$: user.model_help_canvas_open_for_static_prompt(staticPrompt)
