{user.model} quick help$: user.model_help_canvas_open()
{user.model} quick help completeness$: user.model_help_canvas_open_completeness()
{user.model} quick help scope$: user.model_help_canvas_open_scope()
{user.model} quick help method$: user.model_help_canvas_open_method()
{user.model} quick help style$: user.model_help_canvas_open_style()
{user.model} quick help direction$: user.model_help_canvas_open_directional()
{user.model} quick help examples$: user.model_help_canvas_open_examples()

{user.model} show grammar$: user.model_help_canvas_open_for_last_recipe()
{user.model} quick help {user.staticPrompt}$: user.model_help_canvas_open_for_static_prompt(staticPrompt)
