import json
import subprocess
import sys
import unittest
from pathlib import Path
from typing import TYPE_CHECKING

if not TYPE_CHECKING:

    class MakeAxisRegenerateTests(unittest.TestCase):
        def test_axis_regenerate_target_produces_artifacts(self) -> None:
            """Guardrail: axis-regenerate target should run clean and emit artifacts."""

            repo_root = Path(__file__).resolve().parents[1]
            result = subprocess.run(
                ["make", "axis-regenerate"],
                cwd=str(repo_root),
                capture_output=True,
                text=True,
                check=False,
            )
            if result.returncode != 0:
                self.fail(
                    "make axis-regenerate failed:\n"
                    f"exit: {result.returncode}\nstdout:\n{result.stdout}\nstderr:\n{result.stderr}"
                )
            self.assertIn("Axis catalog validation passed.", result.stdout)

            generated_py = repo_root / "tmp" / "axisConfig.generated.py"
            generated_md = repo_root / "tmp" / "readme-axis-tokens.md"
            generated_json = repo_root / "tmp" / "axisConfig.json"
            generated_catalog = repo_root / "tmp" / "axisCatalog.json"
            generated_cheatsheet = repo_root / "tmp" / "readme-axis-cheatsheet.md"
            generated_static_prompts = repo_root / "tmp" / "static-prompt-docs.md"
            generated_readme_axis = repo_root / "tmp" / "readme-axis-lists.md"
            generated_readme_axis_section = repo_root / "tmp" / "readme-axis-readme.md"
            generated_static_prompt_readme = repo_root / "tmp" / "static-prompt-readme.md"

            for artifact in (
                generated_py,
                generated_md,
                generated_json,
                generated_catalog,
                generated_cheatsheet,
                generated_static_prompts,
                generated_readme_axis,
                generated_readme_axis_section,
                generated_static_prompt_readme,
            ):
                self.assertTrue(
                    artifact.exists(),
                    f"Expected {artifact} to be generated by axis-regenerate",
                )

            payload = json.loads(generated_json.read_text(encoding="utf-8"))
            self.assertIsInstance(payload, dict, "axisConfig.json should contain a mapping")
            catalog_payload = json.loads(generated_catalog.read_text(encoding="utf-8"))
            self.assertIn("axes", catalog_payload)
            self.assertIn("axis_list_tokens", catalog_payload)
            self.assertIsInstance(catalog_payload["axes"], dict)
            self.assertIsInstance(catalog_payload["axis_list_tokens"], dict)
            cheat_text = generated_cheatsheet.read_text(encoding="utf-8")
            self.assertIn("Axis Cheat Sheet", cheat_text)
            self.assertIn("Completeness (`completenessModifier`)", cheat_text)
            static_docs = generated_static_prompts.read_text(encoding="utf-8")
            self.assertIn("Other static prompts", static_docs)
            self.assertIn("defaults:", static_docs)
            readme_axis_text = generated_readme_axis.read_text(encoding="utf-8")
            self.assertIn("Completeness (`completenessModifier`)", readme_axis_text)
            self.assertIn("Scope (`scopeModifier`)", readme_axis_text)
            axis_section_text = generated_readme_axis_section.read_text(encoding="utf-8")
            self.assertIn("Completeness (`completenessModifier`)", axis_section_text)
            static_prompt_readme_text = generated_static_prompt_readme.read_text(encoding="utf-8")
            self.assertIn("Static prompt catalog", static_prompt_readme_text)

else:
    if not TYPE_CHECKING:
        class MakeAxisRegenerateTests(unittest.TestCase):
            @unittest.skip("Test harness unavailable outside unittest runs")
            def test_placeholder(self) -> None:
                pass
