"""Ground method prompt (spike/craft-token-refactor branch).

This is the SSOT for the ground method's prompt injection text.
It is NOT generated; edit directly here, then run `make bar-grammar-update`
to propagate changes through to downstream grammar files.

Note: ground is a method token (axisConfig.py), not a task token.
"""


def build_ground_prompt() -> str:
    """Return the ground method prompt string.

    Spike definition: ground = recursive ambiguity resolution in Ground properties block.
    """
    return (
        "The response must produce a 'Ground properties:' block before any test, implementation step, tool call, or task reasoning begins. "
        "If the request admits more than one reasonable interpretation, the chosen interpretation must first be declared on a line beginning exactly: "
        "'Interpretation: <chosen interpretation>' — "
        "all subsequent properties are derived exclusively from this interpretation. "
        "Before writing the first 'property [N]:' line, verify that an 'Interpretation:' line appears above it if the request admits multiple readings; "
        "if the request is ambiguous and no Interpretation: line is present, emit one now — a 'property [N]:' line that appears without a preceding Interpretation: line "
        "when the request admits multiple readings does not satisfy this protocol. "
        "If the request is unambiguous and no Interpretation: line is required, the request itself is the chosen interpretation. "
        "Every property must be derivable from the explicit constraints of the chosen interpretation. "
        "A property that introduces a constraint not implied by those constraints is out of scope and must not appear in the block. "
        "Each property is written on its own line beginning 'property [N]:' followed by a candidate definition intended to have a single unambiguous denotation. "
        "Two independent readers applying the same interpretation must reach the same conclusion about whether a construction satisfies the property. "
        "Step 1 establishes the canonical formal definition; a property need not already be expressed formally when first written. "
        "Apply the following recursive decomposition procedure to every retained property. "
        "Initially, the candidate retained properties are the property [N] entries in the Ground properties block; "
        "a property enters the retained set only after canonicalization and scope validation. "
        "Every property that can enter the retained set — including each initial property [N], each property added during the completeness phase, and each property produced by a merge — "
        "must not constrain an internal mechanism, architecture, algorithm, or representation as its primary subject unless the chosen interpretation explicitly requires that subject; "
        "a property that constrains an internal subject without that explicit requirement is out of scope and must not appear in the retained set. "
        "Externally observable status is evaluated independently of internal-subject status and is not itself a gate for retained-set entry. "
        "Scope validation is applied to the canonical definition produced by Step 1, not to the provisional surface form. "
        "A property is atomic when the recursive decomposition procedure reaches Step 4 and no valid split exists. "
        "Step 1 — Canonicalize the property. "
        "Emit: '§ formality check: property [N]: \"<verbatim definition>\" — [formal | informal: <reason>]'. "
        "If informal, rewrite as a typed mathematical expression, a logical predicate (∀, ∃, ⇒, ⇔), or a formally defined relation, "
        "and emit '§ rewritten: property [N]: \"<new definition>\"', then repeat the formality check on the rewritten definition. "
        "Continue until the formality check concludes formal. "
        "The definition confirmed formal in the final check is the canonical definition for this property — "
        "no subsequent step may quote a definition not yet confirmed formal. "
        "After canonicalization, verify that the chosen interpretation has established an accessible-observation boundary. "
        "If it has not, emit 'Interpretation refinement required: <what the boundary must specify>' and refine the Interpretation: line before evaluating scope. "
        "Then verify scope: if the canonical definition constrains an internal mechanism, architecture, algorithm, or representation as its primary subject "
        "without that subject being explicitly required by the chosen interpretation, reject the property as out of scope and do not retain it. "
        "Externally observable status is evaluated independently of internal-subject status; a property is not rejected merely because its subject is inaccessible, "
        "only because its primary subject is an internal mechanism not required by the interpretation. "
        "Step 2 — Introduce provisional sub-properties. "
        "Introduce provisional candidate sub-properties whose conjunction is proposed to represent the current property: "
        "'property [Na]: <definition>' and 'property [Nb]: <definition>'. "
        "Apply the canonicalization procedure (Step 1) to each provisional sub-property before proceeding. "
        "The resulting canonical definitions replace the provisional definitions for all subsequent split evaluation. "
        "The labels [Na] and [Nb] continue to identify the resulting canonical definitions after replacement. "
        "Split evidence is attached to the canonical definitions of the current property and its provisional sub-properties, "
        "and to the falsifying constructions emitted in the split test, at the moment the split test is emitted. "
        "Any modification to any of those definitions or constructions after the split test is emitted voids that evidence; "
        "the split evidence must then be regenerated against the current canonical state before the split may be accepted. "
        "Step 3 — Evaluate split validity. "
        "Before evaluating the split, verify that the chosen interpretation determines an accessible-observation boundary: "
        "the set of outputs, behaviors, states, and interactions that the party responsible for determining whether the request was satisfied "
        "can access without inspecting the implementation. "
        "If the chosen interpretation does not determine that boundary, emit 'Interpretation refinement required: <what the boundary must specify>' "
        "and emit or refine the Interpretation: line to supply it. "
        "An interpretation refinement voids the entire current retained-property tree, all previously derived properties, and all split evidence, "
        "and restarts property derivation and recursive decomposition from the request constraints under the refined interpretation; "
        "any previously emitted split test is void and does not constitute a completed split test for the current canonical state. "
        "After the accessible-observation boundary has been established and the current property, its provisional sub-properties, and their split evidence have been regenerated under the current interpretation, "
        "emit exactly one non-void split test for the current canonical state: "
        "'§ split test: property [Na]: \"<verbatim canonical definition>\" — falsified by <construction>; "
        "property [Nb]: \"<verbatim canonical definition>\" — falsified by <construction>; these falsifiers are independent.' "
        "The quoted definitions must match the immediately preceding canonical provisional definitions verbatim. "
        "A split may be accepted only if its split test, quoted definitions, falsifying constructions, and interpretation are identical to the non-void state against which the split test was emitted. "
        "A split succeeds only if: the original property is logically equivalent to the conjunction of the accepted sub-properties (P ⇔ (PNa ∧ PNb)); "
        "each quoted falsifier violates exactly its quoted property while satisfying the other; "
        "both falsifiers are admissible constructions within the chosen interpretation; "
        "and neither accepted sub-property constrains an internal mechanism, architecture, algorithm, or representation as the primary subject of the constraint, "
        "unless that mechanism is explicitly required by the chosen interpretation. "
        "A sub-property constrains an internal subject when its canonical definition makes an internal mechanism, architecture, algorithm, or representation the primary subject of the constraint — "
        "this classification is independent of whether that subject happens to be externally observable. "
        "A sub-property is externally observable when its truth value can be determined solely from the accessible-observation boundary of the chosen interpretation, without inspecting the implementation. "
        "These two criteria are distinct: a property can concern an internal subject yet still be externally observable (for example, when the interpretation explicitly exposes that subject through its output contract), "
        "and a property can concern an external subject yet still be inaccessible if the interpretation does not expose the relevant behavior. "
        "The split condition rejects properties whose primary subject is internal and not explicitly required — not merely properties that happen to be inaccessible. "
        "Step 4 — Recurse or mark atomic. "
        "If the split succeeds, replace the original property with the accepted canonical sub-properties "
        "and apply this same recursive decomposition procedure (Steps 1–4) independently to each accepted sub-property. "
        "If no valid split exists, emit: '§ split test: property [N]: \"<verbatim canonical definition>\" — atomic, no valid split: <reason>.' "
        "The quoted definition must match the retained canonical property verbatim. "
        "Apply this procedure to every retained property until all have reached Step 4 with no valid split. "
        "After all retained properties are atomic, emit a completeness check: "
        "'§ completeness check: \"<request constraints verbatim>\" / <P1 expression> / <P2 expression> / ...' — "
        "the request constraints must be quoted verbatim from the explicit constraints of the request as clarified by the chosen interpretation; "
        "interpretive assumptions made to resolve ambiguity and observation-boundary definitions are not themselves request constraints unless they were explicit constraints of the original request; "
        "every retained atomic property expression must appear exactly once, separated by ' / '; "
        "a '§ completeness check:' line that omits the request constraints or omits any retained property expression does not satisfy this requirement. "
        "Immediately after the completeness check, attempt to identify one explicit request constraint that is not logically entailed by the conjunction of the retained atomic property expressions. "
        "If such a constraint exists, emit '§ properties complete? no' — "
        "add one new property covering that explicit constraint, perform the required split testing, and repeat the completeness check. "
        "Only when every explicit request constraint is logically entailed by the conjunction of the retained atomic property expressions may the response emit '§ properties complete? yes' — "
        "a '§ properties complete? yes' line without a preceding completeness check does not satisfy this protocol. "
        "After completeness has been established, verify observational independence. "
        "A retained property is observationally independent if there exists at least one admissible construction that violates that property while satisfying every other retained property. "
        "Any retained property that is not observationally independent is observationally redundant and must be removed or merged, "
        "provided doing so does not reduce coverage of the explicit request constraints. "
        "Any property produced by a merge is a new property and must enter the recursive decomposition procedure (Steps 1–4) as a newly derived property before being added to the retained set. "
        "If a merge or removal changes the retained property set, the current completeness and independence results are void; "
        "re-run the recursive decomposition procedure for every newly introduced property, "
        "then re-establish completeness and observational independence over the resulting retained set. "
        "The Ground properties block is complete only when all retained properties simultaneously satisfy: "
        "they are derived from the chosen interpretation; they are atomic; "
        "their conjunction logically entails every explicit request constraint; "
        "they are observationally independent; they introduce no out-of-scope constraints, including internal mechanism constraints not explicitly required by the chosen interpretation. "
        "When all conditions are met, emit '§ ground complete' as the final line of the Ground properties block — "
        "this sentinel may not appear before '§ properties complete? yes' in the transcript. "
        "Any test, implementation step, tool call, or task reasoning that appears before '§ ground complete' does not satisfy this protocol; "
        "if task reasoning begins and '§ ground complete' has not yet appeared, emit the Ground properties block in full and '§ ground complete' before continuing."
    )
