"""Ground method prompt (spike/craft-token-refactor branch).

This is the SSOT for the ground method's prompt injection text.
It is NOT generated; edit directly here, then run `make bar-grammar-update`
to propagate changes through to downstream grammar files.

Note: ground is a method token (axisConfig.py), not a task token.
"""


def build_ground_prompt() -> str:
    """Return the ground method prompt string.

    Spike definition: ground = recursive ambiguity resolution in Ground properties block.
    """
    return (
        "The response must produce a 'Ground properties:' block before any test, implementation step, tool call, or task reasoning begins. "
        "If the request admits more than one reasonable interpretation, the chosen interpretation must first be declared on a line beginning exactly: "
        "'Interpretation: <chosen interpretation>' — "
        "all subsequent properties are derived exclusively from this interpretation. "
        "Before writing the first 'property [N]:' line, verify that an 'Interpretation:' line appears above it if the request admits multiple readings; "
        "if the request is ambiguous and no Interpretation: line is present, emit one now — a 'property [N]:' line that appears without a preceding Interpretation: line "
        "when the request admits multiple readings does not satisfy this protocol. "
        "If the request is unambiguous and no Interpretation: line is required, the request itself is the chosen interpretation. "
        "Every property must be derivable from the explicit constraints of the chosen interpretation. "
        "A property that introduces a constraint not implied by those constraints is out of scope and must not appear in the block. "
        "Each property is written on its own line beginning 'property [N]:' followed by a candidate definition. "
        "Step 1 establishes the canonical formal definition; a property need not already be expressed formally when first written. "
        "The canonical definition must be expressed in formal notation: a typed mathematical expression, a logical predicate (∀, ∃, ⇒, ⇔), or a formally defined relation. "
        "Natural-language prose alone is not a canonical definition, regardless of how precisely it is phrased. "
        "The canonical definition must have a single unambiguous denotation such that two independent readers applying the same interpretation "
        "reach the same conclusion about whether any given construction satisfies the property. "
        "Every property entering the retained set must have a formal canonical definition before it can be retained, quoted in 'Retained properties:', or governed by any downstream token. "
        "Apply the following recursive decomposition procedure to every retained property. "
        "Initially, the candidate properties are the property [N] entries in the Ground properties block; "
        "a property enters the retained set only after canonicalization and scope validation. "
        "Every property that can enter the retained set — including each initial property [N], each property added during the completeness phase, each property produced by a merge, and each property introduced during audit-driven Ground re-entry — "
        "must have as its primary subject the requested artifact or outcome itself: a required behavior, state, output, interface, or other condition explicitly imposed by the chosen interpretation. "
        "A property must not have as its primary subject the process used to produce, implement, test, review, validate, inspect, measure, or verify the requested artifact or outcome, unless that process is itself an explicit constraint of the request. "
        "Evidence about a property is not the property itself. Tests, assertions, review artifacts, checklists, tool results, validation files, implementation-process artifacts, and other verification evidence may establish or falsify a property but must not be promoted into a Ground property merely because they are necessary to verify it. "
        "A property must not be retained merely because it is a conjunction of in-scope and out-of-scope conditions: a conjunction property is subject to scope validation of each conjunct independently; any conjunct whose primary subject is a process, evidence artifact, or mechanism not explicitly required by the interpretation renders the entire conjunction out of scope unless the offending conjunct is removed before retention. "
        "A property must not constrain an internal mechanism, architecture, algorithm, or representation as its primary subject unless the chosen interpretation explicitly requires that subject. "
        "Admission principle: a property is admissible into the Ground property set only if it constrains the state of the requested artifact as that artifact is observed at the accessible-observation boundary — the condition the delivering artifact must satisfy for the party the request is for to consider the request met — and its truth-value remains invariant as the production, delivery, and verification process is varied while the observed delivered artifact is held fixed. "
        "This admission test is stated as what a property must be, not what it must not be: run it by holding the observed delivered artifact fixed and varying the entire process that produced, delivered, reviewed, or verified it; the property is admissible exactly when its truth-value does not change under that variation, because only then does it constrain the artifact the requester receives rather than the means of producing or handing it over. "
        "A candidate whose truth-value can change under that variation while the observed delivered artifact is unchanged has not met the admission principle and does not enter the property set — this holds even when the chosen interpretation has named that process element, because naming a means of production or delivery in the interpretation does not convert it into a state of the delivered artifact. "
        "Apply the admission principle before the subject-scope check below. "
        "Scope classification of the primary subject must occur before canonicalization can proceed: if the candidate property's primary subject is not the requested artifact or outcome, the property is out of scope and must be rejected before Step 1 is entered. "
        "Canonicalization may formalize a property's definition but may not change its primary subject from the requested artifact or outcome to a process, mechanism, or evidence artifact. "
        "Subject-stability test: replace the implementation and verification process completely while preserving the same requested artifact or outcome. "
        "If the property can become false solely because the implementation, test, review, validation, or verification process changed while the requested artifact or outcome remains the same, the property is out of scope unless that process is explicitly required by the request. "
        "This scope test applies recursively to every property and sub-property produced during decomposition, completeness, merging, or audit-driven Ground re-entry. "
        "Externally observable status is evaluated independently of internal-subject status and is not itself a gate for retained-set entry. "
        "Scope validation is applied to the canonical definition produced by Step 1, not to the provisional surface form — but the pre-canonicalization subject-scope check must already have passed before Step 1 is entered. "
        "A property may contain multiple logical predicates, verification conditions, evidence requirements, or procedural checks without being non-atomic. "
        "Recursive decomposition does not decompose a property's formal definition into its logical conjuncts merely because those conjuncts are independently testable or formally expressible. "
        "Recursive decomposition is concerned only with independently meaningful request constraints, not with decomposition of the evidence, verification, or implementation conditions used to establish that the property holds. "
        "A candidate sub-property is not a distinct constraint merely because it is: "
        "(a) an independently testable predicate; "
        "(b) an assertion in a regression guard; "
        "(c) a verification step or review check; "
        "(d) evidence used to establish the parent property; "
        "(e) a condition required by the implementation or test harness; or "
        "(f) a logical conjunct of the parent's formal definition. "
        "Such a predicate remains part of the parent property unless the explicit request constraints independently require it. "
        "In particular, if a property P can be verified by checking Q ∧ R ∧ S, this does not make Q, R, and S separate Ground properties unless the original request independently requires Q, R, or S — Q, R, and S are verification conditions of P, not properties of the requested outcome. "
        "A property is atomic when the recursive decomposition procedure reaches Step 4 and no valid split into independently meaningful request constraints exists. "
        "Step 1 — Canonicalize the property. "
        "Emit: '§ formality check: property [N]: \"<verbatim definition>\" — [formal | informal: <reason>]'. "
        "If informal, rewrite as a typed mathematical expression, a logical predicate (∀, ∃, ⇒, ⇔), or a formally defined relation, "
        "and emit '§ rewritten: property [N]: \"<new definition>\"', then repeat the formality check on the rewritten definition. "
        "Continue until the formality check concludes formal. "
        "The definition confirmed formal in the final check is the canonical definition for this property — "
        "no subsequent step may quote a definition not yet confirmed formal. "
        "After canonicalization, verify that the chosen interpretation has established an accessible-observation boundary. "
        "If it has not, emit 'Interpretation refinement required: <what the boundary must specify>' and refine the Interpretation: line before evaluating scope. "
        "Any interpretation refinement at this point voids the current canonical definition and all downstream scope, split, and retained-set state for this and any previously processed property under the prior interpretation, "
        "and restarts property derivation from the request constraints under the refined interpretation. "
        "Then verify scope: if the canonical definition constrains an internal mechanism, architecture, algorithm, or representation as its primary subject "
        "without that subject being explicitly required by the chosen interpretation, reject the property as out of scope and do not retain it. "
        "Externally observable status is evaluated independently of internal-subject status; a property is not rejected merely because its subject is inaccessible, "
        "only because its primary subject is an internal mechanism not required by the interpretation. "
        "After scope validation, apply the minimality check: if the canonical definition is over-specific — meaning there exists an admissible construction that satisfies the chosen interpretation yet falsifies the property — the property is over-specific and must be weakened to the weakest condition the chosen interpretation entails before it can be retained. "
        "A property is over-specific when it excludes an admissible construction that the chosen interpretation would nonetheless accept as satisfying the request: the property names a particular way of satisfying a request constraint as though the request required that particular way, when the interpretation would accept other constructions equally. "
        "To weaken, replace the canonical definition with the least restrictive predicate that is still logically entailed by the explicit constraints of the chosen interpretation, such that no admissible construction satisfying the interpretation falsifies the weakened property; then re-run the formality check on the weakened definition. "
        "The chosen interpretation, not the raw request, is the weakening floor: specificity the interpretation explicitly requires is entailed and must be preserved, while specificity present only as an incidental feature of one satisfying construction must be removed. "
        "This minimality check is the dual of the later completeness check: completeness ensures the retained properties are not collectively weaker than the interpretation requires; minimality ensures no individual property is stronger than the interpretation requires. "
        "For each property, immediately after the minimality check and before Step 2, emit a line beginning '§ minimality: property [N]:' recording the outcome of that check, in one of exactly two forms: "
        "'§ minimality: property [N]: over-specific — weakened to \"<new canonical definition>\"' when an admissible construction satisfying the chosen interpretation falsifies the property, followed by re-running the formality check on the weakened definition; "
        "or '§ minimality: property [N]: minimal — most specific sub-term: \"<verbatim sub-term of this property's canonical definition>\"; candidate relaxation: <admissible construction that weakens or drops that sub-term>; rejected: <reason that construction violates the chosen interpretation>' when none does. "
        "The minimal form must exhibit this witnessed relaxation attempt: the most specific sub-term is the narrowest literal, constant, named value, fixed set, or bound appearing in the canonical definition; the candidate relaxation is a concrete admissible construction that generalizes or removes exactly that sub-term; and the rejection reason shows that construction fails the chosen interpretation, which is what justifies retaining the sub-term. "
        "A bare 'minimal' verdict — one that asserts no construction falsifies the property without quoting a most specific sub-term, without naming a candidate relaxation construction, and without showing that construction violates the interpretation — does not satisfy this protocol; if the candidate relaxation instead satisfies the interpretation, the property is over-specific and the over-specific form must be emitted instead. "
        "The minimality check runs on every property without exception — including properties whose primary constraint appears obviously general, properties already in formal notation, and properties introduced during the completeness phase or produced by a merge; no property may be exempted on the ground that it is evidently minimal. "
        "A property that reaches Step 2 without an emitted '§ minimality:' line for that property, in one of these two forms, does not satisfy this protocol; if the '§ minimality:' line for a property has not appeared, emit it before introducing any provisional sub-property. "
        "Step 2 — Introduce provisional sub-properties. "
        "Introduce provisional candidate sub-properties whose conjunction is proposed to represent the current property: "
        "'property [Na]: <definition>' and 'property [Nb]: <definition>'. "
        "Apply the canonicalization procedure (Step 1) to each provisional sub-property before proceeding. "
        "The resulting canonical definitions replace the provisional definitions for all subsequent split evaluation. "
        "The labels [Na] and [Nb] continue to identify the resulting canonical definitions after replacement. "
        "Split evidence is attached to the canonical definitions of the current property and its provisional sub-properties, "
        "and to the falsifying constructions emitted in the split test, at the moment the split test is emitted. "
        "Any modification to any of those definitions or constructions after the split test is emitted voids that evidence; "
        "the split evidence must then be regenerated against the current canonical state before the split may be accepted. "
        "Step 3 — Evaluate split validity. "
        "Before evaluating the split, verify that the chosen interpretation determines an accessible-observation boundary: "
        "the set of outputs, behaviors, states, and interactions that the party responsible for determining whether the request was satisfied "
        "can access without inspecting the implementation. "
        "If the chosen interpretation does not determine that boundary, emit 'Interpretation refinement required: <what the boundary must specify>' "
        "and emit or refine the Interpretation: line to supply it. "
        "An interpretation refinement voids the entire current retained-property tree, all previously derived properties, and all split evidence, "
        "and restarts property derivation and recursive decomposition from the request constraints under the refined interpretation; "
        "any previously emitted split test is void and does not constitute a completed split test for the current canonical state. "
        "After the accessible-observation boundary has been established and the current property, its provisional sub-properties, and their split evidence have been regenerated under the current interpretation, "
        "emit exactly one non-void candidate split test for the current canonical state: "
        "'§ split test: property [N]: \"<verbatim canonical definition>\" ⇔ (property [Na]: \"<verbatim canonical definition>\" ∧ property [Nb]: \"<verbatim canonical definition>\"); "
        "property [Na] — falsified by <construction>; "
        "property [Nb] — falsified by <construction>; these falsifiers are independent.' "
        "The quoted definitions for [N], [Na], and [Nb] must match the verbatim canonical definitions confirmed in Step 1 for each respective property. "
        "A split may be accepted only if its split test, quoted definitions, falsifying constructions, and interpretation are identical to the non-void state against which the split test was emitted. "
        "A split succeeds only if: for every admissible construction x, P(x) ⇔ (PNa(x) ∧ PNb(x)) — the original property is logically equivalent to the conjunction of the accepted sub-properties over all admissible constructions; "
        "each quoted falsifier violates exactly its quoted property while satisfying the other; "
        "both falsifiers are admissible constructions within the chosen interpretation; "
        "the candidate split is nontrivial: neither accepted sub-property is logically equivalent to the original property over all admissible constructions, and neither accepted sub-property logically entails the other over all admissible constructions; "
        "each accepted sub-property corresponds to a distinct constraint on the admissible construction under the chosen interpretation that is independently required by the explicit request constraints, and the request itself distinguishes the two sub-constraints at its own granularity — meaning the request separately names, or would be independently judged as failing on, each sub-constraint on its own; "
        "a candidate split is not valid merely because it decomposes the mathematical or definitional structure of a predicate, is not valid merely because each sub-property is independently testable, assertable, or useful as verification evidence, and is not valid merely because the two sub-constraints are logically distinct when the request does not itself distinguish them at its own granularity — if a single request constraint is being divided into finer conditions that the request never separately names or judges, the property is atomic at the request's granularity and must not be split; "
        "and neither accepted sub-property constrains an internal mechanism, architecture, algorithm, or representation as the primary subject of the constraint, "
        "unless that mechanism is explicitly required by the chosen interpretation. "
        "A sub-property constrains an internal subject when its canonical definition makes an internal mechanism, architecture, algorithm, or representation the primary subject of the constraint — "
        "this classification is independent of whether that subject happens to be externally observable. "
        "A sub-property is externally observable when its truth value can be determined solely from the accessible-observation boundary of the chosen interpretation, without inspecting the implementation. "
        "These two criteria are distinct: a property can concern an internal subject yet still be externally observable (for example, when the interpretation explicitly exposes that subject through its output contract), "
        "and a property can concern an external subject yet still be inaccessible if the interpretation does not expose the relevant behavior. "
        "The split condition rejects properties whose primary subject is internal and not explicitly required — not merely properties that happen to be inaccessible. "
        "A candidate split can be constructed only if canonical definitions for [Na] and [Nb] have been established and admissible falsifying constructions satisfying the stated falsifier conditions can be produced for both sub-properties. "
        "A candidate split test is accepted when all split-success conditions are satisfied for that non-void candidate; otherwise the candidate split is rejected. "
        "Step 4 — Accept or mark atomic. "
        "A property may be marked atomic only after Step 2 has introduced provisional sub-properties, Step 1 has canonicalized them, and Step 3 has attempted candidate-split construction against the current canonical state. "
        "If the candidate split test is accepted, replace the original property with the accepted canonical sub-properties "
        "and apply this same recursive decomposition procedure (Steps 1–4) independently to each accepted sub-property. "
        "If no candidate split can be constructed, emit: '§ atomic: property [N]: \"<verbatim canonical definition>\" — no candidate split satisfies the construction requirements: <reason>.' "
        "If a candidate split test is emitted and rejected, emit: '§ atomic: property [N]: \"<verbatim canonical definition>\" — candidate split rejected: <reason>.' "
        "A property that represents a single request constraint at the request's own granularity is atomic even if its mathematical or logical expression admits formal decomposition, and even if that decomposition would yield logically distinct sub-conditions; "
        "the nontriviality and distinct-constraint conditions in Step 3 enforce this: a split into sub-properties that merely reformulate the mathematical definition of the predicate, or that subdivides a single request constraint into finer conditions the request never separately names or judges — rather than separating constraints the request itself distinguishes — is invalid and must be rejected as not nontrivial or not corresponding to distinct constraints at the request's granularity. "
        "The quoted definition must match the current canonical definition verbatim. "
        "Apply this procedure to every retained property until all have reached Step 4 and emitted '§ atomic:'. "
        "After all retained properties are atomic, emit a completeness check: "
        "'§ completeness check: \"<request constraints verbatim>\" / <P1 expression> / <P2 expression> / ...' — "
        "the request constraints must be quoted verbatim from the explicit constraints of the original request; "
        "the chosen interpretation determines the meaning of those constraints where the request is ambiguous but does not add, remove, or alter explicit constraints; "
        "interpretive assumptions made to resolve ambiguity and observation-boundary definitions are not themselves request constraints unless they were explicit constraints of the original request; "
        "every retained atomic property expression must appear exactly once, separated by ' / '; "
        "a '§ completeness check:' line that omits the request constraints or omits any retained property expression does not satisfy this requirement. "
        "Immediately after the completeness check, attempt to identify one explicit request constraint that is not logically entailed by the conjunction of the retained atomic property expressions. "
        "If such a constraint exists, emit '§ properties complete? no' — "
        "add one new property covering that explicit constraint, perform the required split testing, and repeat the completeness check. "
        "Only when every explicit request constraint is logically entailed by the conjunction of the retained atomic property expressions may the response emit '§ properties complete? yes' — "
        "a '§ properties complete? yes' line without a preceding completeness check does not satisfy this protocol; "
        "'§ properties complete? yes' certifies completeness only for the retained set existing immediately before that check; "
        "any subsequently committed removal or merge voids that result and requires a new completeness check. "
        "The completeness phase is concerned only with coverage of explicit request constraints; redundancy introduced during this phase is resolved by the subsequent observational-independence phase. "
        "After all retained properties are atomic, enter the Ground completion fixed-point procedure: "
        "first establish completeness for the current retained set; "
        "after '§ properties complete? yes', establish observational independence for that same retained set. "
        "A retained property is observationally independent if there exists at least one admissible construction that violates that property while satisfying every other retained property. "
        "Any retained property that is not observationally independent is observationally redundant and must be resolved — either successfully removed or successfully merged — "
        "provided the resolution does not reduce coverage of the explicit request constraints. "
        "A redundant property remains unresolved until either a removal or a merge replacing it is successfully committed; "
        "a failed merge or failed removal does not resolve the redundancy and requires another valid independence action. "
        "A proposed merge creates a candidate retained set by replacing its source properties with the merged property: "
        "the merged property must first complete canonicalization, scope validation, and recursive decomposition to an atomic state; "
        "once atomic, it replaces its source properties in the candidate retained set. "
        "A proposed removal creates a candidate retained set by removing the selected property; the source retained set remains unchanged until the candidate is validated. "
        "For both merge and removal, the candidate retained set must re-run the completeness-check procedure and observational-independence procedure; "
        "the candidate set may not be committed unless a new '§ completeness check:' is followed by '§ properties complete? yes' and the candidate set satisfies observational independence. "
        "A candidate retained set is committed only if it itself reaches the Ground fixed point — passing both '§ properties complete? yes' and the observational-independence procedure — before it replaces the source retained set; otherwise the candidate is discarded and the source retained set remains authoritative. "
        "If the candidate is committed and the committed change produces any further redundant property, restart the fixed-point procedure with a new completeness check on the resulting retained set. "
        "Otherwise discard the candidate and leave the source retained set unchanged, then attempt another valid independence action for the unresolved redundant property. "
        "Admissible constructions used as falsifiers or independence witnesses are evidence about the truth conditions of properties and do not thereby make the construction's internal mechanism, architecture, algorithm, or representation the primary subject of the property. "
        "Repeat until a retained set simultaneously satisfies completeness and observational independence; when no retained property is observationally redundant, the fixed-point procedure terminates. "
        "The Ground properties block is complete only when all retained properties simultaneously satisfy: "
        "they are derived from the chosen interpretation; they are atomic; "
        "their conjunction logically entails every explicit request constraint; "
        "they are observationally independent; they introduce no out-of-scope constraints, including internal mechanism constraints not explicitly required by the chosen interpretation. "
        "When all conditions are met, immediately before emitting '§ ground complete', emit exactly one 'Retained properties:' line declaring the final retained property set: "
        "'Retained properties: property [N]: \"<verbatim canonical formal definition>\"; property [M]: \"<verbatim canonical formal definition>\"; ...' — "
        "listing every retained property in retained-set order, each quoted definition matching its final canonical formal definition verbatim. "
        "A 'Retained properties:' line that omits any retained property, quotes a natural-language or non-canonical definition, or is not immediately followed by '§ ground complete' does not satisfy this protocol. "
        "A '§ ground complete' line that is not immediately preceded by 'Retained properties:' does not satisfy this protocol. "
        "This sentinel may not appear before '§ properties complete? yes' in the transcript. "
        "'§ ground complete' is a phase-boundary sentinel, not a response-termination condition. "
        "After emitting '§ ground complete', continue with the requested task using the retained atomic properties as the governing constraints for all subsequent task reasoning, tests, implementation steps, and tool calls. "
        "The response must not terminate solely because '§ ground complete' has been emitted. "
        "All subsequent task work must remain consistent with the completed Ground properties; "
        "the Ground properties block is not itself the requested task unless the original request explicitly asks only for property derivation. "
        "Any test, implementation step, tool call, or task reasoning that appears before '§ ground complete' does not satisfy this protocol; "
        "if task reasoning begins and '§ ground complete' has not yet appeared, emit the Ground properties block in full and '§ ground complete' before continuing. "
        "After '§ ground complete', continue with the requested task; do not treat the sentinel as terminating the response."
    )
