# Lateral-seed word list — Python SSOT for the `bar build --seed-words` feature.
#
# These are common, concrete, imageable English nouns used as random "oblique
# strategies"-style creative seeds. They are deliberately NOT bar tokens: a seed
# is *content* the model reacts to, not a lens. The list is curated toward
# concrete nouns because abstract words and verbs make weak lateral seeds.
#
# Surfaced via the `lateral_seed_words` key in the exported prompt grammar
# (lib/promptGrammar.prompt_grammar_payload), which propagates to all four
# grammar JSON copies — including web/static — via `make bar-grammar-update`.
#
# To add words: keep them lowercase, single-token, purely alphabetic, and
# concrete/imageable. Keep the list sorted and free of duplicates.

from typing import List

LATERAL_SEED_WORDS: List[str] = [
    "abacus", "acorn", "airport", "alarm", "album", "anchor", "anthill", "anvil",
    "apple", "apron", "aquarium", "arch", "armor", "arrow", "attic", "avalanche",
    "avenue", "axe", "backpack", "badge", "bakery", "balcony", "ballad", "balloon",
    "bamboo", "bandage", "banjo", "barn", "barrel", "basement", "basket", "battery",
    "beach", "beacon", "beak", "beam", "bean", "beard", "bed", "beehive", "bell",
    "bellows", "belt", "bench", "berry", "bicycle", "binder", "birdcage", "biscuit",
    "blanket", "blender", "blossom", "boat", "bobbin", "boiler", "bolt", "bonfire",
    "bonnet", "bookcase", "boot", "bottle", "boulder", "bouquet", "bowl", "brick",
    "bridge", "briefcase", "bristle", "broom", "bucket", "buckle", "bulb", "bunker",
    "buoy", "burrow", "button", "cabin", "cable", "cactus", "cage", "cake", "camera",
    "campfire", "canal", "candle", "cannon", "canoe", "canvas", "canyon", "cap",
    "cape", "capsule", "carousel", "carpet", "carriage", "cart", "cascade", "casket",
    "castle", "catapult", "cauldron", "cavern", "cellar", "cello", "chain", "chair",
    "chalk", "chandelier", "channel", "chapel", "charcoal", "chariot", "chart",
    "chasm", "chessboard", "chimney", "chisel", "cinder", "cistern", "citadel",
    "clamp", "clarinet", "claw", "cliff", "cloak", "clock", "closet", "clover",
    "coal", "coast", "cobweb", "cockpit", "cocoon", "coffin", "coil", "coin",
    "collar", "column", "comb", "comet", "compass", "conch", "cone", "container",
    "cork", "corridor", "cottage", "couch", "courtyard", "crab", "cradle", "crane",
    "crater", "crayon", "crest", "crib", "crossbow", "crown", "crumb", "crutch",
    "crystal", "cube", "cupboard", "curtain", "cushion", "cymbal", "dagger", "dam",
    "dashboard", "deck", "den", "desk", "diamond", "dial", "diary", "dice", "ditch",
    "dock", "domino", "doorway", "drawbridge", "drawer", "drift", "drill", "drum",
    "dune", "dungeon", "dynamite", "eagle", "easel", "echo", "eclipse", "eel",
    "eggshell", "elbow", "elevator", "ember", "engine", "envelope", "escalator",
    "estuary", "factory", "fan", "fang", "faucet", "feather", "fence", "fern",
    "ferry", "fiddle", "fin", "fireplace", "fishhook", "fist", "flag", "flake",
    "flame", "flask", "flint", "float", "flood", "flute", "foam", "foghorn", "foil",
    "footbridge", "footprint", "forge", "fork", "fortress", "fountain", "fox",
    "frame", "freckle", "furnace", "gable", "gadget", "gallows", "garden", "gargoyle",
    "gasket", "gate", "gauntlet", "gavel", "gear", "geyser", "glacier", "glass",
    "globe", "glove", "glue", "goblet", "gondola", "gong", "gorge", "grate", "grave",
    "gravel", "greenhouse", "grid", "grill", "groove", "grotto", "guitar", "gull",
    "gully", "gutter", "hammer", "hammock", "hangar", "harbor", "harness", "harp",
    "harpoon", "hatch", "hatchet", "hawk", "hay", "haystack", "headlight", "hearth",
    "hedge", "helmet", "hinge", "hive", "hollow", "honeycomb", "hood", "hook",
    "hoop", "horizon", "hornet", "horseshoe", "hose", "hourglass", "hovel", "hull",
    "hut", "hydrant", "iceberg", "icicle", "igloo", "ingot", "inkwell", "iris",
    "iron", "island", "ivy", "jacket", "jar", "javelin", "jetty", "jewel", "jigsaw",
    "joint", "journal", "jug", "jungle", "kayak", "keg", "kennel", "kettle", "key",
    "keyboard", "keyhole", "kiln", "kite", "knapsack", "knife", "knob", "knot",
    "label", "labyrinth", "ladder", "ladle", "lagoon", "lamp", "lantern", "lasso",
    "latch", "lattice", "lava", "leaf", "ledge", "ledger", "lever", "library",
    "lid", "lighthouse", "lightning", "lily", "limb", "linen", "lock", "locket",
    "locomotive", "loft", "log", "loom", "lounge", "magnet", "mailbox", "mallet",
    "manor", "mantle", "map", "marble", "marsh", "mask", "mast", "mat", "maze",
    "meadow", "medal", "membrane", "mesh", "microscope", "millstone", "mine",
    "mirror", "mist", "mitten", "moat", "mold", "monolith", "moon", "moss", "moth",
    "mound", "mountain", "mug", "mural", "mushroom", "nail", "necklace", "needle",
    "nest", "net", "nook", "notch", "nozzle", "oar", "oasis", "obelisk", "orchard",
    "organ", "ornament", "outlet", "oven", "overpass", "owl", "package", "paddle",
    "padlock", "pagoda", "pail", "palette", "pane", "panel", "pantry", "parachute",
    "parasol", "parcel", "pasture", "path", "pavement", "pavilion", "paw", "pearl",
    "pebble", "pedal", "pendant", "pendulum", "pennant", "pepper", "petal", "pewter",
    "piano", "pickaxe", "picket", "pier", "pigment", "pillar", "pillow", "pin",
    "pinecone", "pipe", "piston", "pit", "pitcher", "pivot", "plank", "plateau",
    "platform", "playground", "plaza", "pliers", "plow", "plug", "plume", "pocket",
    "pod", "pole", "pond", "porch", "portrait", "pot", "pottery", "pouch", "prairie",
    "press", "prism", "propeller", "puddle", "pulley", "pump", "pumpkin", "puppet",
    "pyramid", "quarry", "quill", "quilt", "quiver", "radiator", "raft", "rafter",
    "railing", "rake", "ramp", "rampart", "ravine", "razor", "reed", "reef", "reel",
    "reservoir", "ribbon", "ridge", "rifle", "rig", "ring", "ripple", "river",
    "rivet", "roof", "root", "rope", "rotor", "rowboat", "rubble", "rudder", "rug",
    "ruin", "runway", "sack", "saddle", "safe", "sail", "sandbar", "sandbox",
    "sapling", "sash", "satchel", "saucer", "saw", "scaffold", "scale", "scar",
    "scarf", "scepter", "scissors", "sconce", "scoop", "screen", "screw", "scroll",
    "scythe", "seal", "seam", "seashell", "seed", "seesaw", "shackle", "shaft",
    "shard", "shawl", "shed", "shell", "shelf", "shield", "shingle", "ship", "shoe",
    "shovel", "shrine", "shutter", "sickle", "sieve", "silo", "sink", "siphon",
    "skate", "skeleton", "sketch", "skillet", "skull", "skylight", "slab", "sled",
    "slide", "sling", "slope", "sluice", "smoke", "snare", "snorkel", "snowflake",
    "socket", "sofa", "spade", "spanner", "spark", "sparrow", "spear", "spigot",
    "spindle", "spiral", "spire", "splint", "sponge", "spool", "spoon", "spore",
    "spout", "spring", "sprocket", "spur", "stable", "stadium", "staff", "stage",
    "staircase", "stake", "stalactite", "stall", "stamp", "stapler", "starfish",
    "statue", "steeple", "stem", "stencil", "step", "stethoscope", "stew", "stile",
    "stilt", "stirrup", "stitch", "stockade", "stone", "stool", "stopper", "stove",
    "strap", "straw", "stream", "street", "string", "stump", "submarine", "sundial",
    "swamp", "sword", "syringe", "table", "tack", "tail", "talon", "tambourine",
    "tank", "tapestry", "tarp", "teapot", "telescope", "tendril", "tent", "thicket",
    "thimble", "thistle", "thorn", "thread", "throne", "thumbtack", "ticket", "tide",
    "tile", "timber", "tin", "toboggan", "tomb", "tongs", "toolbox", "tooth", "torch",
    "tornado", "tower", "trail", "trampoline", "trapdoor", "tray", "treasure",
    "trellis", "trench", "triangle", "tripod", "trolley", "trombone", "trough",
    "trowel", "trumpet", "trunk", "tub", "tube", "tumbleweed", "tundra", "tunnel",
    "turbine", "turnstile", "turret", "turtle", "tusk", "tweezers", "twig", "umbrella",
    "urn", "valve", "vane", "vase", "vault", "veil", "vent", "vessel", "vial",
    "village", "vine", "vineyard", "violin", "vise", "volcano", "wagon", "wall",
    "wand", "wardrobe", "warehouse", "waterfall", "wax", "weathervane", "web", "wedge",
    "weir", "well", "whale", "wharf", "wheel", "wheelbarrow", "whip", "whisker",
    "whistle", "wick", "windmill", "window", "windowsill", "wing", "wire", "wok",
    "wreath", "wrench", "yacht", "yardstick", "yarn", "yoke", "zipper",
]

__all__ = ["LATERAL_SEED_WORDS"]
