"""Inspect history telemetry exports and emphasise guardrail metadata.

This helper prints a concise summary for telemetry payloads generated by
``history-axis-export-telemetry.py`` so manual reviews can quickly identify the
associated guardrail target and key gating statistics.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any, Iterable

DEFAULT_FIELDS: tuple[str, ...] = (
    "guardrail_target",
    "summary_path",
    "total_entries",
    "gating_drop_total",
    "gating_drop_rate",
    "streaming_status",
    "last_drop_message",
    "last_drop_code",
    "streaming_last_drop_message",
    "streaming_last_drop_code",
)


def _load_payload(path: Path) -> dict[str, Any]:
    try:
        text = path.read_text(encoding="utf-8")
    except FileNotFoundError as exc:  # pragma: no cover - defensive guard
        raise SystemExit(f"telemetry file not found: {path}") from exc
    try:
        data = json.loads(text)
    except json.JSONDecodeError as exc:  # pragma: no cover - defensive guard
        raise SystemExit(f"telemetry file is not valid JSON: {path}") from exc
    if not isinstance(data, dict):  # pragma: no cover - defensive guard
        raise SystemExit(f"telemetry payload must be an object: {path}")
    return data


def _format_value(value: Any) -> str:
    if isinstance(value, str):
        stripped = value.strip()
        return stripped or "none"
    if value is None:
        return "none"
    if isinstance(value, (int, float)) and not isinstance(value, bool):
        return str(value)
    if isinstance(value, (list, dict)):
        try:
            return json.dumps(value, separators=(",", ":"))
        except (TypeError, ValueError):  # pragma: no cover - defensive guard
            return "<unserializable>"
    return str(value)


def _iter_fields(fields: Iterable[str]) -> Iterable[str]:
    seen: set[str] = set()
    for field in fields:
        if field not in seen:
            seen.add(field)
            yield field


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "telemetry_paths",
        metavar="telemetry",
        nargs="+",
        type=Path,
        help="One or more telemetry JSON files produced by history-axis-export-telemetry.py",
    )
    parser.add_argument(
        "--field",
        "-f",
        action="append",
        dest="fields",
        help=(
            "Additional payload fields to print. Repeat the flag to include multiple "
            "fields. Defaults include guardrail target and key gating stats."
        ),
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    fields = list(DEFAULT_FIELDS)
    if args.fields:
        fields.extend(args.fields)

    for index, path in enumerate(args.telemetry_paths):
        payload = _load_payload(path)
        if index > 0:
            print()  # separator line between files
        print(f"telemetry: {path}")
        for field in _iter_fields(fields):
            value = payload.get(field, "none")
            print(f"  {field}: {_format_value(value)}")
    return 0


if __name__ == "__main__":  # pragma: no cover - CLI entry
    raise SystemExit(main())
